### ISSUE TITLE
Changing the News command.

### ISSUE THREAD

**Issue by ghost** [Aceheliflyer/AceBot#6]
You should make it that the %news command shows news of the latest tweaks, and things. You could get some people to do it for you if you don't have the time. 

Ex: We just added a new command %picture. It randomly gets a picture off the internet and posts it.

**Comment by AriRexouium** [comment]
I will do `%news` but not `%picture`. The bot is aimed towards moderation.

**Comment by ghost** [comment]
%picture was not something you were suppost to make, it was just an example to give you an idea of what %news will look like.
